<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>MyTabCloud</title>
        
        
        <!-- blueprintcss dependency -->
        <?php $this->headLink()->appendStylesheet('/mytabcloud/public/css/blueprint/screen.css', 'screen, projection') ?>
        <?php $this->headLink()->appendStylesheet('/mytabcloud/public/css/blueprint/print.css', 'print') ?>
        <?php $this->headLink()->appendStylesheet('/mytabcloud/public/css/smoothness/jquery-ui-1.8.11.custom.css') ?>
        <?php $this->headLink()->appendStylesheet('/mytabcloud/public/css/mytabcloud.css') ?>
        <?php $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Arvo:regular,bold') ?>
        <?php echo $this->headLink(); ?>
        <!--[if lte IE 8]>
        <link rel="stylesheet" href="/mytabcloud/public/css/blueprint/ie.css" type="text/css" media="screen, projection" />
        <![endif]-->
        
        <?php $this->headScript()->appendFile('/mytabcloud/public/js/jquery.min.js'); ?>
        <?php $this->headScript()->appendFile('/mytabcloud/public/js/jquery-ui-1.8.11.custom.min.js'); ?>
        <?php $this->javascriptHelper(); ?>
        <?php echo $this->headScript(); ?>
        
                
    </head>
    <body>
    	<div class="general_container">
	    	<div class="header_container">
	        	<div class="container">
				    <div class="span-24 last header">
				        <h1><a href="<?php $this->url(array('controller' => 'index', 'action' => 'index'), 'default', true); ?>"><img src="/mytabcloud/public/images/tabber_logo.png" alt="Tabber, your online tab editor"></img></a></h1>
				        <?php echo $this->navigation()->menu(); ?>
				    </div>	
				</div>
	    	</div>
	    	<div class="body_container">
	        	<div class="container">
				    <div class="span-18 colborder">
				    	<?php echo $this->layout()->content ?>	
					</div>
					<div class="span-5 last">
						<?php echo $this->action('signin', 'user'); ?>
					</div>
				</div>
			</div>
		</div>
		<div class="footer">
			<div class="container">
				<div class="span-8">
			        <h3 style="font-family:'Arvo';color:#d3b397;">Tabber</h3>
					<p>About</p>
					<p>Terms of service</p>
			    </div>
			    <div class="span-8">
			        <h3 style="font-family:'Arvo';color:#d3b397;">Help</h3>
					<p>F.A.Q.</p>
			    </div>
			    <div class="span-8 last">
			        <h3 style="font-family:'Arvo';color:#d3b397;">Contact</h3>
					<p>Contact us</p>
					<p>Follow us</p>
			    </div>
			    
			</div>	
		</div>
        
       
    </body>
</html>