<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>MyTabCloud</title>
        
        
        <!-- blueprintcss dependency -->
        <?php $this->headLink()->appendStylesheet('/mytabcloud/public/css/blueprint/screen.css', 'screen, projection') ?>
        <?php $this->headLink()->appendStylesheet('/mytabcloud/public/css/blueprint/print.css', 'print') ?>
        <?php $this->headLink()->appendStylesheet('/mytabcloud/public/css/mytabcloud.css') ?>
        <?php echo $this->headLink(); ?>
        
        <!--[if lte IE 8]>
        <link rel="stylesheet" href="/mytabcloud/public/css/blueprint/ie.css" type="text/css" media="screen, projection" />
        <![endif]-->       
        
                
    </head>
    <body>
        <div class="container">
		    <div class="span-24 last">
		        <h1><a href="<?php $this->url(array('controller' => 'index', 'action' => 'index'), 'default', true); ?>">MyTabCloud : Online Tab Editor</a></h1>
		    </div>
		    <div class="span-18 colborder">
		    	<?php echo $this->layout()->content ?>	
			</div>
			<div class="span-5 last">
				<?php echo $this->action('signin', 'user'); ?>
			</div>
			<div class="span-24 last footer">
		        <img src="/mytabcloud/public/images/zend_powered.png" /><br />
		        Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution 3.0 License
		    </div>
		</div>
        
       
    </body>
</html>