<?php
	echo $this->form('searchform',array(
									'enctype' => 'application/x-www-form-urlencoded',
									'method' => 'post',
									'action' => $this->url(array('controller' => 'search', 'action' => 'index'), 'default', true)
								));
	
	echo $this->formHidden('formname', 'searchform', null);
	echo $this->formText('q', '', array());
	echo $this->formSubmit('searchsubmit', 'Search', array());
?>
	</form>

<?php if($this->results) { ?>
<h3>Users</h3>
<?php 
	foreach($this->users as $usr) {
		echo $usr->getName() . " (" . $usr->getLogin() . ")<br />";
	} 
?>
<br />
<h3>Tabs</h3>
<?php 
	foreach($this->tabs as $tab) {
		echo $tab->getTitle() . " (" . $tab->getArtist() . ")<br />";
	} 
?>
<br />
<?php } ?>