<?php
	echo $this->form('searchform',array(
									'enctype' => 'application/x-www-form-urlencoded',
									'method' => 'post',
									'action' => $this->url(array('controller' => 'search', 'action' => 'index'), 'default', true)
								));
	
	echo $this->formHidden('formname', 'searchform', null);
	echo $this->formText('q', $this->q, array());
	echo $this->formSubmit('searchsubmit', 'Search', array());
?>
	</form>

<?php if($this->results) { ?>
<h3>Users</h3>
<?php 
	if(sizeof($this->users)>0) {
		foreach($this->users as $usr) {
			echo '<a href="' . $this->url(array('controller' => 'user', 'action' => 'profile', 'id' => $usr->getId()), 'default', true) . '">' . $usr->getName() . "</a> (" . $usr->getLogin() . ")<br />";
		}
	} 
?>
<br />
<h3>Tabs</h3>
<?php 
	if(sizeof($this->tabs)>0) {
		foreach($this->tabs as $tab) {
			echo '<a href="' . $this->url(array('controller' => 'tab', 'action' => 'display', 'id' => $tab->getId()), 'default', true) . '">' . $tab->getTitle() . "</a> (" . $tab->getArtist() . ")<br />";
		}	 
	}
?>
<br />
<?php } ?>