<div class="container">
	<div class="span-18 colborder">
		<div class="profile_container">
			<div class="profile_image"><?php echo $this->gravatarHelper(GRAVATAR_SIZE_PROFILE, $this->user->getMail()); ?></div>
			<div class="profile_content">
				<h2><?php echo $this->user->getName(); ?></h2>
				<div class="profile_line last">
					<div class="profile_line_title">Login :</div>
					<div class="profile_line_value"><?php echo $this->user->getLogin(); ?></div>
					<div class="profile_clear"></div>
				</div>
				<div class="profile_line last">
					<div class="profile_line_title">E-Mail :</div>
					<div class="profile_line_value"><?php echo $this->user->getMail(); ?></div>
					<div class="profile_clear"></div>
				</div>
				<div class="profile_line last">
					<div class="profile_line_title">Inscription date :</div>
					<div class="profile_line_value"><?php echo $this->user->getCreated(); ?></div>
					<div class="profile_clear"></div>
				</div>
			</div>
		</div>
	</div>
	<div class="span-5 last">
		<?php if ($this->selfProfile) { ?>
		<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'edit'), 'default', true); ?>" class="button"><span class="icon pen"></span>Edit my profile</a>
		<?php } else { ?>
		<?php switch(MyTabCloud_Friendship::friendshipRequested($this->asker, $this->user->getId())) {
				case MyTabCloud_Friendship::NO_FRIENDSHIP:
					echo '<a href="' . $this->url(array('controller' => 'user', 'action' => 'friendship', 'friend' => $this->user->getId()), 'default', true) . '" class="button"><span class="icon user"></span>Add to friends</a>';
					break;
				case MyTabCloud_Friendship::PENDING_REQUEST:
					echo '<a href="#" class="button"><span class="icon user"></span>Friend request pending</a>';
					break;
				case MyTabCloud_Friendship::FRIENDSHIP:
					echo "friends";
					break;
				}
		?>
		
		<?php } ?>
	</div>
</div>
	