<?php
	// Si l'utilisateur n'est pas loggé, on affiche le formulaire de login
	if(!$this->user()) {
		$this->form->setAction($this->url());
		echo $this->loginMessage;
		//echo $this->form;
		?>
		<form id="signin" enctype="application/x-www-form-urlencoded" method="post" action="/mytabcloud/public/">
		<input type="hidden" name="formname" value="signin" id="formname" />
		<input type="text" placeholder="Your login" name="login" id="login" value="" />
		<input type="password" placeholder="Your password" name="password" id="password" value="" />
		<a href="#" id="signin_button" class="button"><span class="user icon"></span>Log in</a>
		<input type="submit" value="submit" name="submit" class="hidden">
		</form>
		<br />
		<?php				
		echo "<a href=".$this->signupURL.">New user ? Sign up !</a>";
	// Sinon on affiche son nom et le lien pour se déconnecter
	} else {
		echo "<table><tr><td>";
			echo "Welcome, " . $this->user() . "<br />";
			echo '<a href="'.$this->signoutURL.'">Logout</a>';
		echo '</td><td class="gravatar">';
			echo $this->gravatarHelper();
		echo "</td></tr></table>";		
	}