<?php ?>
<?php
    if($this->user()) {
        if($this->display_form) {
?>
        <map name='nb_strings_map' id="nb_strings_map">                        
           <area shape='rect' coords='0,11,20,22' href="javascript:fctDown('#nb_strings', 1);" alt="Down" />                        
           <area shape='rect' coords='0,0,20,10' href="javascript:fctUp('#nb_strings', 10);" alt="Up" />                        
        </map>
        
        <map name='capo_map' id="capo_map">                        
           <area shape='rect' coords='0,11,20,22' href="javascript:fctDown('#capo', 0);" alt="Down" />                        
           <area shape='rect' coords='0,0,20,10' href="javascript:fctUp('#capo', 25);" alt="Up" />                        
        </map>
        
        <form id="createtab" enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->url(array('controller' => 'tab', 'action' => 'create'), 'default', true); ?>">
        <div class="container center">
        	<?php echo $this->formHidden('formname', $this->form_name, null); ?>
        	
            <div id="tab_pane" class="span-24">
            	<ul>
            		<li><a href="#tab-song">Song Information</a></li>
            		<li><a href="#tab-config">Tab configuration</a></li>
					<li><a href="#tab-content">Tab content</a></li>
            	</ul>
	            <div id="tab-song">
		            <table>
		                <tr>
		                    <td><?php echo $this->formLabel('artist', 'Artist', array('class' => 'required')); ?></td>
		                    <td><?php echo $this->formText('artist', '', null); ?></td>
		                </tr>                     
		                <tr>
		                    <td><?php echo $this->formLabel('title', 'Title', array('class' => 'required')); ?></td>                     
		                    <td><?php echo $this->formText('title', '', null); ?></td>
		                </tr>
		                <tr>
		                    <td><?php echo $this->formLabel('description', 'Description', array('class' => 'required')); ?></td>                     
		                    <td><?php echo $this->formTextarea('description', '', array('class' => 'tab_description')); ?></td>
		                </tr>
		            </table>
	                <!-- <dt id="title-label"><label for="tuning" class="required">Tuning</label></dt>                     
	                <dd id="title-element"><input type="text" name="tuning" id="tuning" value="<?php echo $this->params['tuning']; ?>" /></dd> -->
	            </div>
            	<div id="tab-config">
		            <table>
						<tr>
							<td><?php echo $this->formLabel('preset', 'Preset', array('class' => 'required')); ?></td>
							<td>
								<?php echo $this->formSelect('preset', '1', null, $this->presets); ?>
							</td>
							<td><?php echo $this->formLabel('visibility', 'Visibility', array('class' => 'required')); ?></td>
							<td>
								<select name="visibility" id="visibility">
									<option value="public">Public</option>
									<option value="private">Private</option>
								</select>
							</td>
						</tr>
						<tr>
		                    <td><?php echo $this->formLabel('nb_strings', 'Strings', array('class' => 'required')); ?></td>                     
		                    <td>
								<?php echo $this->formText('nb_strings', DEFAULT_STRINGS, array('size' => '5')); ?>
		                        <img src="<?php echo $this->baseUrl(); ?>/images/updown.png" width="14" height="19" style="vertical-align:middle;" usemap="#nb_strings_map" alt="Up Down"></img>
		                    </td>
							
							<td><?php echo $this->formLabel('instrument', 'Instrument', array('class' => 'required')); ?></td>
							<td>
								<?php echo $this->formSelect('instrument', '1', null, $this->instruments); ?>
							</td>
		                </tr>
		                <tr>
		                    <td><?php echo $this->formLabel('capo', 'Capo', array('class' => 'required')); ?></td>                     
		                    <td>
								<?php echo $this->formText('capo', 0, array('size' => '5')); ?>
		                        <img src="<?php echo $this->baseUrl(); ?>/images/updown.png" width="14" height="19" style="vertical-align:middle;" usemap="#capo_map" alt="Up Down"></img>
		                    </td>
		                </tr>
		                <tr>
		                    <td><?php echo $this->formLabel(null, 'Tuning', array('class' => 'required')); ?></td>                     
		                    <td id="td_tuning">
							<?php
								for($tun_str = 0 ; $tun_str < DEFAULT_STRINGS ; $tun_str++) {
									echo '<div id="tuning_div_' . $tun_str . '">';
									echo $this->formText('tuning_' . $tun_str, 'E4', array('size' => '3'));
									echo '<img src="' . $this->baseUrl() .'/images/updown.png" width="14" height="19" class="updownimg" usemap="#map_tuning_'.$tun_str.'" alt="Up Down"></img>';
									echo '<map name="map_tuning_'.$tun_str.'" id="map_tuning_'.$tun_str.'">';
									echo '	<area shape="rect" coords="0,11,20,22" href="javascript:fctTuneDown(\'#tuning_'.$tun_str.'\');" alt="Down" />';
									echo '	<area shape="rect" coords="0,0,20,10" href="javascript:fctTuneUp(\'#tuning_'.$tun_str.'\');" alt="Up" />';                        
									echo '</map>';
									echo '</div>';
								}
							?>
		                    </td>
		                </tr>
	               </table>  
				</div>
				<div id="tab-content">
					<div id="tab_display">
						<?php echo $this->tab_display; ?>
					</div>
					<!-- <p class="add_line"><a href="javascript:addTabLine();">Add Line</a></p> -->
					<div class="button">
						<div class="left_button"></div>
						<div class="center_button">Add Line</div>
						<div class="right_button">+</div>
					</div>
					
				</div>
            </div>
         </div>   
        
                
        <dl class="zend_form">
			<?php echo $this->formSubmit('submit', 'Save', null); ?>
        </dl>
        </form>
<?php
        } else {
            echo $this->message;
        }
    } else {
        echo "Veuillez vous connecter";
    }
    
?>