<?php

$visibilities = array(
	MyTabCloud_Constants::VISIBILITY_PUBLIC => 'Public',
	MyTabCloud_Constants::VISIBILITY_FRIENDS => 'Friends',
	MyTabCloud_Constants::VISIBILITY_PRIVATE => 'Private'
);

if($this->has_tab) {
?>	

<?php
    if($this->user()) {
        if($this->display_form) {
?>
        <map name='nb_strings_map' id="nb_strings_map">                        
           <area shape='rect' coords='0,11,20,22' href="javascript:fctDown('#nb_strings', 1);" alt="Down" />                        
           <area shape='rect' coords='0,0,20,10' href="javascript:fctUp('#nb_strings', 10);" alt="Up" />                        
        </map>
        
        <map name='capo_map' id="capo_map">                        
           <area shape='rect' coords='0,11,20,22' href="javascript:fctDown('#capo', 0);" alt="Down" />                        
           <area shape='rect' coords='0,0,20,10' href="javascript:fctUp('#capo', 25);" alt="Up" />                        
        </map>
        
        <form id="edittab" enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->url(array('controller' => 'tab', 'action' => 'edit', 'id' => $this->params['id']), 'default', true); ?>">
        <div class="container">
			<?php echo $this->formHidden('formname', $this->form_name, null); ?>
        	
            <div id="tab_pane" class="span-24">
            	<ul>
            		<li><a href="#tab-song">Song Information</a></li>
            		<li><a href="#tab-config">Tab configuration</a></li>
					<li><a href="#tab-content">Tab content</a></li>
            	</ul>
	            <div id="tab-song">
		            <table>
		                <tr>
							<td><?php echo $this->formLabel('artist', 'Artist', array('class' => 'required')); ?></td>
		                    <td><?php echo $this->formText('artist', $this->params['artist'], null); ?></td>
		                </tr>                     
		                <tr>
							<td><?php echo $this->formLabel('title', 'Title', array('class' => 'required')); ?></td>                     
		                    <td><?php echo $this->formText('title', $this->params['title'], null); ?></td>
		                </tr>
		                <tr>
							<td><?php echo $this->formLabel('description', 'Description', array('class' => 'required')); ?></td>                     
		                    <td><?php echo $this->formTextarea('description', $this->params['description'], array('class' => 'tab_description')); ?></td>
		                </tr>
		            </table>
	                <!-- <dt id="title-label"><label for="tuning" class="required">Tuning</label></dt>                     
	                <dd id="title-element"><input type="text" name="tuning" id="tuning" value="<?php echo $this->params['tuning']; ?>" /></dd> -->
				</div>
	            <div id="tab-config">
		            <table>
						<tr>
							<td><?php echo $this->formLabel('preset', 'Preset', array('class' => 'required')); ?></td>
							<td>
								<?php echo $this->formSelect('preset', '1', null, $this->presets); ?>
							</td>
							<td><?php echo $this->formLabel('visibility', 'Visibility', array('class' => 'required')); ?></td>
							<td>
								<?php echo $this->formSelect('visibility', $this->params['visibility'], null, $visibilities); ?>
							</td>
						</tr>
						<tr>
							<td><?php echo $this->formLabel('nb_strings', 'Strings', array('class' => 'required')); ?></td>                     
		                    <td>
								<?php echo $this->formText('nb_strings', $this->params['nb_strings'], array('size' => '5')); ?>
		                        <img src='<?php echo $this->baseUrl(); ?>/images/updown.png' width='14' height='19' style="vertical-align:middle;" usemap='#nb_strings_map'></img>
		                    </td>
							<td><?php echo $this->formLabel('instrument', 'Instrument', array('class' => 'required')); ?></td>
							<td>
								<?php echo $this->formSelect('instrument', $this->params['instrument'], null, $this->instruments); ?>
							</td>
		                </tr>
		                <tr>
		                    <td><?php echo $this->formLabel('capo', 'Capo', array('class' => 'required')); ?></td>
							 <td>
								<?php echo $this->formText('capo', $this->params['capo'], array('size' => '5')); ?>
		                        <img src='<?php echo $this->baseUrl(); ?>/images/updown.png' width='14' height='19' style="vertical-align:middle;" usemap='#capo_map'></img>
		                    </td>
		                </tr>
		                <tr>
		                    <td><label class="required">Tuning</label></td>                     
		                    <td id="td_tuning">
							<?php
								for($tun_str = 0 ; $tun_str < $this->params['nb_strings'] ; $tun_str++) {
									echo '<div id="tuning_div_' . $tun_str . '">';
									echo $this->formText('tuning_' . $tun_str, $this->params['tuning'][$tun_str], array('size' => '3'));
									echo '<img src="' . $this->baseUrl() .'/images/updown.png" width="14" height="19" class="updownimg" usemap="#map_tuning_'.$tun_str.'" alt="Up Down"></img>';
									echo '<map name="map_tuning_'.$tun_str.'" id="map_tuning_'.$tun_str.'">';
									echo '	<area shape="rect" coords="0,11,20,22" href="javascript:fctTuneDown(\'#tuning_'.$tun_str.'\');" alt="Down" />';
									echo '	<area shape="rect" coords="0,0,20,10" href="javascript:fctTuneUp(\'#tuning_'.$tun_str.'\');" alt="Up" />';                        
									echo '</map>';
									echo '</div>';
								}
							?>
		                    </td>
		                </tr>
	               </table>   
	            </div>
				<div id="tab-content">
					<div id="tab_display">
						<?php echo $this->tab_display; ?>
					</div>
					<p class="add_line"><a class="button" href="javascript:addTabLine();"><span class="plus icon"></span>Add Line</a></p>
					
					
				</div>
				</div>
			</div>
		 
		<div style="width:100%; text-align:center; margin-top:10px;">
			<a href="javascript:$('#edittab').submit();" class="positive button" style="margin-right:5px;"><span class="icon check"></span>Save</a>
         </div>     
                
		
        </form>
<?php
        } else {
            echo $this->message;
        }
    } else {
        echo "Veuillez vous connecter";
    }
    
?>	


<?php		
} else { echo $this->message; }
?>
