<?php 
    if($this->user()) {
        echo "Ici, la liste des tablatures de " . $this->user() . ".<br>";
        
        foreach($this->tabs as $tab) {
            echo '<a href="' . $this->url(array('controller' => 'tab', 'action' => 'display', 'id' => $tab->getId()), 'default', true) . '">' . $tab->getArtist() . " - " . $tab->getTitle() . "</a><br>";
        }
        
    } else {
        echo "Veuillez vous connecter";
    }
?>